name: Terraform

on:

  push:
    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master" ]

  workflow_dispatch:
jobs:
 PAD:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform initialize
        id: init
        run: terraform init
        working-directory: "./module"

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: "./module"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: "./module"

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan
        working-directory: "./module"
      

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "./module"
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: "./module"